import java.util.Scanner;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1,2,3,5,8,13,21,34,55,89
//By considering the terms in the Fibonacci sequence whose values do not exceed N , find the sum of the even-valued terms.
public class EulerProblem2 {
  public static void main(String[] args) {
    Scanner in = new Scanner(System.in);
    int t = in.nextInt();
    for(int a0 = 0; a0 < t; a0++){
      long n = in.nextLong();
      System.out.println(getSumOfEvenFib(n));
    }
  }

  private static long getSumOfEvenFib(long n){
    long a = 1;
    long b = 2;
    long sum = 0;
    while (b <= n) {
      if(b % 2 == 0){
        sum += b;
      }
      long temp = a;
      a = b;
      b = temp + b;
    }

    return sum;
  }
}
